version: 1.0.0.{build}
configuration: Release
platform: Any CPU

build_script:
- msbuild "Bohrium.targets" /t:clean /v:n /maxcpucount /nodeReuse:false
- msbuild "Bohrium.Tools.SpecflowReportTool.msbuild" /t:compile /property:Configuration="Debug" /v:n /maxcpucount /nodeReuse:false
- msbuild "Bohrium.Tools.BDDManagementTool.msbuild" /t:compile /property:Configuration="Debug" /v:n /maxcpucount /nodeReuse:false
- msbuild "Bohrium.Tools.SpecflowReportTool.msbuild" /t:compile /property:Configuration="Release" /v:n /maxcpucount /nodeReuse:false
- msbuild "Bohrium.Tools.BDDManagementTool.msbuild" /t:compile /property:Configuration="Release" /v:n /maxcpucount /nodeReuse:false
- msbuild "Bohrium.Tools.SpecflowReportTool.msbuild" /t:deploy-packages /property:CI_BUILD_NUMBER="%APPVEYOR_BUILD_NUMBER%" /v:n /maxcpucount /nodeReuse:false

test_script:

after_test:

artifacts:
- path: build\DeployArtifacts\*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/bohrium-tools/
  api_key:
    secure: 8b646fdb-9eb3-4f4c-a517-2ff974a9633d
  skip_symbols: true
  on:
    branch: master