version: 1.0.0.{build}
configuration: Release
platform: Any CPU

branches:
  only:
  - master

build_script:
- msbuild "Bohrium.targets" /t:clean /v:n /maxcpucount /nodeReuse:false
- msbuild "Bohrium.Tools.SpecflowReportTool.msbuild" /t:compile /property:Configuration="Debug" /v:n /maxcpucount /nodeReuse:false
- msbuild "Bohrium.Tools.BDDManagementTool.msbuild" /t:compile /property:Configuration="Debug" /v:n /maxcpucount /nodeReuse:false
- msbuild "Bohrium.Tools.SpecflowReportTool.msbuild" /t:compile /property:Configuration="Release" /v:n /maxcpucount /nodeReuse:false
- msbuild "Bohrium.Tools.BDDManagementTool.msbuild" /t:compile /property:Configuration="Release" /v:n /maxcpucount /nodeReuse:false

test:
  assemblies: test\**\*.Test.dll
  categories:
    except:
    - sample

after_test:
- msbuild "Bohrium.Tools.SpecflowReportTool.msbuild" /t:deploy-packages /property:CI_BUILD_NUMBER="%APPVEYOR_BUILD_NUMBER%" /v:n /maxcpucount /nodeReuse:false

artifacts:
- path: build\DeployArtifacts\*.nupkg

deploy_script:
- msbuild "Bohrium.Tools.SpecflowReportTool.msbuild" /t:deploy /property:CI_BUILD_NUMBER="%APPVEYOR_BUILD_NUMBER%" /v:n /maxcpucount /nodeReuse:false